# bootstrap: macos
- shell:
    - description: Install Homebrew
      quiet: true
      command: |
        if ! command -v brew &> /dev/null
        then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi

- create:
    - ~/.config/kitty

- link:
    ~/Library/Preferences/espanso:
      if: '[ `uname` = Darwin ]'
      path: espanso
    ~/.config/karabiner.edn:
      if: '[ `uname` = Darwin ]'
      path: karabiner/karabiner.edn
    ~/.hammerspoon:
      if: '[ `uname` = Darwin ]'
      path: hammerspoon
    ~/.mackup.cfg:
      if: '[ `uname` = Darwin ]'
      path: mackup/mackup.cfg
    ~/.Brewfile:
      if: '[ `uname` = Darwin ]'
      path: Brewfile
    ~/.config/kitty/kitty.conf:
      if: '[ `uname` = Darwin ]'
      path: kitty/kitty.conf
    ~/.config/kitty/base16-solarized-dark-256.conf:
      if: '[ `uname` = Darwin ]'
      path: kitty/base16-solarized-dark-256.conf
    ~/.skhdrc:
      if: '[ `uname` = Darwin ]'
      path: skhd/skhdrc
    ~/.yabairc:
      if: '[ `uname` = Darwin ]'
      path: yabai/yabairc
    ~/.yabai_focus_display:
      if: '[ `uname` = Darwin ]'
      path: yabai/yabai_focus_display

- brew:
    - assh
    - git
    - fd
    - fzf
    - htop
    - tmux
    - pyenv
    - pyenv-virtualenv
    - ripgrep
    - ffmpeg
    - zsh
    - yqrashawn/goku/goku

- tap:
    - homebrew/cask-fonts

- cask:
    - appcleaner
    - contexts
    - bigwig-club/brew/upic
    - font-fira-code
    - hammerspoon
    - iterm2
    - jetbrains-toolbox
    - karabiner-elements
    - kitty
    - keka
    - mos
    - maczip
    - obsidian
    - plexamp
    - postman
    - raycast
    - syncthing
    - tailscale
    - telegram-desktop
    - visual-studio-code
    - warp
    - zerotier-one
